from enum import Enum
from typing import Any, Dict, Iterable, Iterator, List, Optional, Sequence, Tuple, Union, overload
from datetime import datetime, date

__version__: str

class ImageInfo:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    extension: Any
    name: Any
    path: Any

def XLAboveAverageRule(*args: Any, **kwargs: Any) -> Any: ...
class XLAlignment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def horizontal(self, *args: Any, **kwargs: Any) -> Any: ...
    def indent(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_horizontal(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_indent(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_rotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_shrink_to_fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_vertical(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_wrap_text(self, *args: Any, **kwargs: Any) -> Any: ...
    def shrink_to_fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertical(self, *args: Any, **kwargs: Any) -> Any: ...
    def wrap_text(self, *args: Any, **kwargs: Any) -> Any: ...

class XLAlignmentStyle:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Bottom: Any
    Center: Any
    CenterContinuous: Any
    Distributed: Any
    Fill: Any
    General: Any
    Justify: Any
    Left: Any
    Right: Any
    Top: Any

class XLAppProperties:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_heading_pair(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def align_worksheets(self, *args: Any, **kwargs: Any) -> Any: ...
    def append_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_heading_pair(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def increment_sheet_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def prepend_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def property(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_heading_pair(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...

class XLAutoFilter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def filter_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def ref(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_ref(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_ref_range(self, *args: Any, **kwargs: Any) -> Any: ...

class XLAxis:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_max_bounds(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_min_bounds(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_crosses(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_crosses_at(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_date_axis(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_log_scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_major_gridlines(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_major_unit(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_max_bounds(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_min_bounds(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_minor_gridlines(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_minor_unit(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_number_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_orientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_tick_label_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_title(self, *args: Any, **kwargs: Any) -> Any: ...

class XLAxisCrosses:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AutoZero: Any
    Max: Any
    Min: Any

class XLAxisOrientation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    MaxMin: Any
    MinMax: Any

class XLAxisTickLabelPosition:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    High: Any
    Low: Any
    NextToAxis: Any
    None_: Any

class XLBorder:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def diagonal(self, *args: Any, **kwargs: Any) -> Any: ...
    def diagonal_down(self, *args: Any, **kwargs: Any) -> Any: ...
    def diagonal_up(self, *args: Any, **kwargs: Any) -> Any: ...
    def horizontal(self, *args: Any, **kwargs: Any) -> Any: ...
    def left(self, *args: Any, **kwargs: Any) -> Any: ...
    def outline(self, *args: Any, **kwargs: Any) -> Any: ...
    def right(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_diagonal(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_diagonal_down(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_diagonal_up(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_horizontal(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_left(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_outline(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_right(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_top(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_vertical(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...
    def top(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertical(self, *args: Any, **kwargs: Any) -> Any: ...

class XLBorders:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def border_by_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCalcStatus:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Circular: Any
    Empty: Any
    Error: Any
    Ok: Any

class XLCalculationEngine:
    dirty_count: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calc_cell_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_cache(self, *args: Any, **kwargs: Any) -> Any: ...
    def dependencies(self, *args: Any, **kwargs: Any) -> Any: ...
    def dependents(self, *args: Any, **kwargs: Any) -> Any: ...
    def extract_dependencies(self, *args: Any, **kwargs: Any) -> Any: ...
    def mark_all_dirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def mark_dirty(self, *args: Any, **kwargs: Any) -> Any: ...
    def notify_changed(self, *args: Any, **kwargs: Any) -> Any: ...
    def rebuild(self, *args: Any, **kwargs: Any) -> Any: ...
    def recalculate(self, *args: Any, **kwargs: Any) -> Any: ...
    def recalculate_all(self, *args: Any, **kwargs: Any) -> Any: ...
    def reload_defined_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_input_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_formula_cell(self, *args: Any, **kwargs: Any) -> Any: ...

    formula_count: Any
class XLCalculationOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    auto_track_changes: Any
    circular_error_token: Any
    max_depth: Any
    max_expanded_deps: Any
    propagate_dirty: Any
    set_full_calc_on_load: Any
    use_defined_names: Any
    write_back: Any

class XLCell:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_note(self, *args: Any, **kwargs: Any) -> Any: ...
    def cell_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def cell_reference(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy_from(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_string(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def offset(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_cell_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCellAddressError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLCellFormat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def alignment(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_alignment(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_border(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_fill(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_font(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_number_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def border_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def font_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def locked(self, *args: Any, **kwargs: Any) -> Any: ...
    def number_format_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_alignment(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_border(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_fill(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_font(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_number_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_apply_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_border_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_fill_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_font_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_locked(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_number_format_id(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCellFormats:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cell_format_by_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...

def XLCellIsRule(*args: Any, **kwargs: Any) -> Any: ...
class XLCellKey:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def address(self, *args: Any, **kwargs: Any) -> Any: ...
    def parse(self, *args: Any, **kwargs: Any) -> Any: ...
    def qualified_address(self, *args: Any, **kwargs: Any) -> Any: ...
    def valid(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCellRange:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def address(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def bottom_right(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def intersect(self, *args: Any, **kwargs: Any) -> Any: ...
    def num_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def num_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_border_outline(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def top_left(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCellReference:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def address(self, *args: Any, **kwargs: Any) -> Any: ...
    def column(self, *args: Any, **kwargs: Any) -> Any: ...
    def row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_address(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row_and_column(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCfOperator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    BeginsWith: Any
    Between: Any
    ContainsText: Any
    EndsWith: Any
    Equal: Any
    GreaterThan: Any
    GreaterThanOrEqual: Any
    LessThan: Any
    LessThanOrEqual: Any
    NotBetween: Any
    NotContains: Any
    NotEqual: Any

class XLCfRule:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def above_average(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_formulas(self, *args: Any, **kwargs: Any) -> Any: ...
    def dxf_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def equal_average(self, *args: Any, **kwargs: Any) -> Any: ...
    def formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def formulas(self, *args: Any, **kwargs: Any) -> Any: ...
    def operator_(self, *args: Any, **kwargs: Any) -> Any: ...
    def percent(self, *args: Any, **kwargs: Any) -> Any: ...
    def priority(self, *args: Any, **kwargs: Any) -> Any: ...
    def rank(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_above_average(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_dxf_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_equal_average(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_operator(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_percent(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_priority(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_rank(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_std_dev(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_stop_if_true(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_text(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_time_period(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def std_dev(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop_if_true(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...
    def text(self, *args: Any, **kwargs: Any) -> Any: ...
    def time_period(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCfRules:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cf_rule_by_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def max_priority_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def renumber_priorities(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_priority(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...

class XLCfTimePeriod:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Last7Days: Any
    LastMonth: Any
    LastWeek: Any
    NextMonth: Any
    NextWeek: Any
    ThisMonth: Any
    ThisWeek: Any
    Today: Any
    Tomorrow: Any
    Yesterday: Any

class XLCfType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AboveAverage: Any
    BeginsWith: Any
    CellIs: Any
    ColorScale: Any
    ContainsBlanks: Any
    ContainsErrors: Any
    ContainsText: Any
    DataBar: Any
    DuplicateValues: Any
    EndsWith: Any
    Expression: Any
    IconSet: Any
    NotContainsBlanks: Any
    NotContainsErrors: Any
    NotContainsText: Any
    TimePeriod: Any
    Top10: Any
    UniqueValues: Any

class XLCfvoType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Formula: Any
    Invalid: Any
    Max: Any
    Min: Any
    Number: Any
    Percent: Any
    Percentile: Any

class XLChart:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_bubble_series(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_series(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_series_ref(self, *args: Any, **kwargs: Any) -> Any: ...
    def axis(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_chart_area_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_gap_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_hole_size(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_legend_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_overlap(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_plot_area_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_rotation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_series_marker(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_series_smooth(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_data_labels(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_data_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_title(self, *args: Any, **kwargs: Any) -> Any: ...
    def x_axis(self, *args: Any, **kwargs: Any) -> Any: ...
    def y_axis(self, *args: Any, **kwargs: Any) -> Any: ...

class XLChartAnchor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    col: Any
    height: Any
    name: Any
    row: Any
    width: Any

class XLChartSeries:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_error_bars(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_trendline(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_data_labels(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_data_labels_from_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_data_point_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_line_dash(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_line_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_marker_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_smooth(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_title(self, *args: Any, **kwargs: Any) -> Any: ...

class XLChartType:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Area: Any
    Area3D: Any
    Area3DPercentStacked: Any
    Area3DStacked: Any
    AreaPercentStacked: Any
    AreaStacked: Any
    Bar: Any
    Bar3D: Any
    Bar3DPercentStacked: Any
    Bar3DStacked: Any
    BarPercentStacked: Any
    BarStacked: Any
    Bubble: Any
    Column: Any
    Column3D: Any
    Column3DPercentStacked: Any
    Column3DStacked: Any
    ColumnPercentStacked: Any
    ColumnStacked: Any
    Doughnut: Any
    Line: Any
    Line3D: Any
    LinePercentStacked: Any
    LineStacked: Any
    Pie: Any
    Pie3D: Any
    Radar: Any
    RadarFilled: Any
    RadarMarkers: Any
    Scatter: Any
    ScatterLine: Any
    ScatterLineMarker: Any
    ScatterMarker: Any
    ScatterSmooth: Any
    ScatterSmoothMarker: Any
    StockHLC: Any
    StockOHLC: Any
    Surface: Any
    Surface3D: Any
    Surface3DWireframe: Any
    SurfaceWireframe: Any

class XLChartsheet:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def color(self, *args: Any, **kwargs: Any) -> Any: ...
    def index(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_selected(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_selected(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_visibility(self, *args: Any, **kwargs: Any) -> Any: ...
    def visibility(self, *args: Any, **kwargs: Any) -> Any: ...

class XLColor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def alpha(self, *args: Any, **kwargs: Any) -> Any: ...
    def blue(self, *args: Any, **kwargs: Any) -> Any: ...
    def green(self, *args: Any, **kwargs: Any) -> Any: ...
    def hex(self, *args: Any, **kwargs: Any) -> Any: ...
    def red(self, *args: Any, **kwargs: Any) -> Any: ...
    def set(self, *args: Any, **kwargs: Any) -> Any: ...

def XLColorScaleRule(*args: Any, **kwargs: Any) -> Any: ...
class XLColumn:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def width(self, *args: Any, **kwargs: Any) -> Any: ...

class XLComment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def author_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def ref(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_author_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_text(self, *args: Any, **kwargs: Any) -> Any: ...
    def text(self, *args: Any, **kwargs: Any) -> Any: ...
    def valid(self, *args: Any, **kwargs: Any) -> Any: ...

class XLComments:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_author(self, *args: Any, **kwargs: Any) -> Any: ...
    def author(self, *args: Any, **kwargs: Any) -> Any: ...
    def author_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def set(self, *args: Any, **kwargs: Any) -> Any: ...
    def shape(self, *args: Any, **kwargs: Any) -> Any: ...

class XLConditionalFormat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cf_rules(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_sqref(self, *args: Any, **kwargs: Any) -> Any: ...
    def sqref(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...

class XLConditionalFormats:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...

def XLContainsBlanksRule(*args: Any, **kwargs: Any) -> Any: ...
def XLContainsErrorsRule(*args: Any, **kwargs: Any) -> Any: ...
def XLContainsTextRule(*args: Any, **kwargs: Any) -> Any: ...
class XLContentItem:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def path(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLContentType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CalculationChain: Any
    Chart: Any
    ChartColorStyle: Any
    ChartStyle: Any
    Chartsheet: Any
    Comments: Any
    ControlProperties: Any
    CoreProperties: Any
    CustomProperties: Any
    Drawing: Any
    ExtendedProperties: Any
    ExternalLink: Any
    Hyperlink: Any
    Relationships: Any
    SharedStrings: Any
    Styles: Any
    Table: Any
    Theme: Any
    Unknown: Any
    VBAProject: Any
    VMLDrawing: Any
    Workbook: Any
    WorkbookMacroEnabled: Any
    Worksheet: Any

class XLContentTypes:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_override(self, *args: Any, **kwargs: Any) -> Any: ...
    def content_item(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_override(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_content_items(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDataBarColor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def automatic(self, *args: Any, **kwargs: Any) -> Any: ...
    def indexed(self, *args: Any, **kwargs: Any) -> Any: ...
    def rgb(self, *args: Any, **kwargs: Any) -> Any: ...
    def set(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_automatic(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_indexed(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_rgb(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_theme(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_tint(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...
    def theme(self, *args: Any, **kwargs: Any) -> Any: ...
    def tint(self, *args: Any, **kwargs: Any) -> Any: ...

def XLDataBarRule(*args: Any, **kwargs: Any) -> Any: ...
class XLDataValidation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def allow_blank(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_config(self, *args: Any, **kwargs: Any) -> Any: ...
    def config(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def error(self, *args: Any, **kwargs: Any) -> Any: ...
    def error_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def error_title(self, *args: Any, **kwargs: Any) -> Any: ...
    def formula1(self, *args: Any, **kwargs: Any) -> Any: ...
    def formula2(self, *args: Any, **kwargs: Any) -> Any: ...
    def ime_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def operator_(self, *args: Any, **kwargs: Any) -> Any: ...
    def prompt(self, *args: Any, **kwargs: Any) -> Any: ...
    def prompt_title(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_allow_blank(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_date_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_decimal_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_error(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_formula1(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_formula2(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_ime_mode(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_list(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_operator(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_prompt(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_reference_drop_list(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_drop_down(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_error_message(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_input_message(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_sqref(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_text_length_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_time_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_whole_number_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_drop_down(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_error_message(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_input_message(self, *args: Any, **kwargs: Any) -> Any: ...
    def sqref(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDataValidationConfig:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    allow_blank: Any
    error: Any
    error_style: Any
    error_title: Any
    formula1: Any
    formula2: Any
    ime_mode: Any
    operator_: Any
    prompt: Any
    prompt_title: Any
    show_drop_down: Any
    show_error_message: Any
    show_input_message: Any
    type: Any

class XLDataValidationErrorStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Information: Any
    Stop: Any
    Warning: Any

class XLDataValidationOperator:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Between: Any
    Equal: Any
    GreaterThan: Any
    GreaterThanOrEqual: Any
    LessThan: Any
    LessThanOrEqual: Any
    NotBetween: Any
    NotEqual: Any

class XLDataValidationType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Custom: Any
    Date: Any
    Decimal: Any
    List: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    TextLength: Any
    Time: Any
    Whole: Any

class XLDataValidations:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_validation(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def at(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def disable_prompts(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_disable_prompts(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_x_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_y_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def x_window(self, *args: Any, **kwargs: Any) -> Any: ...
    def y_window(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDateTime:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def as_datetime(self, *args: Any, **kwargs: Any) -> Any: ...
    def serial(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDateTimeError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLDefinedName:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def local_sheet_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def refers_to(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_local_sheet_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_refers_to(self, *args: Any, **kwargs: Any) -> Any: ...
    def valid(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDefinedNameIterator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    ...

class XLDefinedNames:
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def all(self, *args: Any, **kwargs: Any) -> Any: ...
    def append(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDocument:
    def __enter__(self) -> XLDocument: ...
    def __exit__(self, *args: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def app_properties(self, *args: Any, **kwargs: Any) -> Any: ...
    def cleanup_shared_strings(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self, *args: Any, **kwargs: Any) -> Any: ...
    def compression_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def content_types(self, *args: Any, **kwargs: Any) -> Any: ...
    def core_properties(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_chart(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_pivot_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def custom_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def default_author(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_custom_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_macro(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_archive_entries(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_archive_entry(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_embedded_images(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_image_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_string(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_string_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_archive_entry(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_macro(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_persons(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_relationships(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_threaded_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_sheet_vml_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_open(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_table_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def open(self, *args: Any, **kwargs: Any) -> Any: ...
    def path(self, *args: Any, **kwargs: Any) -> Any: ...
    def persons(self, *args: Any, **kwargs: Any) -> Any: ...
    def property(self, *args: Any, **kwargs: Any) -> Any: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_as(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_compression_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_custom_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_default_author(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_formula_needs_recalculation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_relationships(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_threaded_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_vml_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def string_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def string_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def styles(self, *args: Any, **kwargs: Any) -> Any: ...
    def validate_package_invariants(self, *args: Any, **kwargs: Any) -> Any: ...
    def validate_sheet_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def workbook(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDrawing:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_scaled_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_shape(self, *args: Any, **kwargs: Any) -> Any: ...
    def image(self, *args: Any, **kwargs: Any) -> Any: ...
    def image_count(self, *args: Any, **kwargs: Any) -> Any: ...

class XLDrawingItem:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def col(self, *args: Any, **kwargs: Any) -> Any: ...
    def description(self, *args: Any, **kwargs: Any) -> Any: ...
    def height(self, *args: Any, **kwargs: Any) -> Any: ...
    def image_binary(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def relationship_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def row(self, *args: Any, **kwargs: Any) -> Any: ...
    def width(self, *args: Any, **kwargs: Any) -> Any: ...

def XLDuplicateValuesRule(*args: Any, **kwargs: Any) -> Any: ...
class XLDxf:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def alignment(self, *args: Any, **kwargs: Any) -> Any: ...
    def border(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill(self, *args: Any, **kwargs: Any) -> Any: ...
    def font(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_font(self, *args: Any, **kwargs: Any) -> Any: ...
    def num_fmt(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...

class XLErrorBarDirection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    X: Any
    Y: Any

class XLErrorBarType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Both: Any
    Minus: Any
    Plus: Any

class XLErrorBarValueType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Custom: Any
    FixedValue: Any
    Percentage: Any
    StandardDeviation: Any
    StandardError: Any

class XLEvalSession:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_current_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_current_sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name_resolver(self, *args: Any, **kwargs: Any) -> Any: ...

class XLException(RuntimeError):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLFill:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def background_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def color(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def pattern_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_background_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_fill_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_pattern_type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFillType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Gradient: Any
    Pattern: Any

class XLFills:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill_by_index(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFilterColumn:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_filters(self, *args: Any, **kwargs: Any) -> Any: ...
    def col_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_custom_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_top10(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFilterLogic:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    And: Any
    Or: Any

class XLFont:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def bold(self, *args: Any, **kwargs: Any) -> Any: ...
    def color(self, *args: Any, **kwargs: Any) -> Any: ...
    def italic(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def scheme(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_bold(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_italic(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_scheme(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_size(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_strikethrough(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_underline(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_vert_align(self, *args: Any, **kwargs: Any) -> Any: ...
    def size(self, *args: Any, **kwargs: Any) -> Any: ...
    def strikethrough(self, *args: Any, **kwargs: Any) -> Any: ...
    def underline(self, *args: Any, **kwargs: Any) -> Any: ...
    def vert_align(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFontSchemeStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Major: Any
    Minor: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')

class XLFonts:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def font_by_index(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFormula:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def get(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFormulaDiagnostic:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    message: Any
    offset: Any

class XLFormulaDiagnosticReporter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def diagnostics(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_full_report(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_errors(self, *args: Any, **kwargs: Any) -> Any: ...
    def report_error(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFormulaEngine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...

class XLFormulaError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def XLFormulaRule(*args: Any, **kwargs: Any) -> Any: ...
class XLHeaderFooter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def align_with_margins(self, *args: Any, **kwargs: Any) -> Any: ...
    def different_first(self, *args: Any, **kwargs: Any) -> Any: ...
    def different_odd_even(self, *args: Any, **kwargs: Any) -> Any: ...
    def even_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def even_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def odd_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def odd_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale_with_doc(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_align_with_margins(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_different_first(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_different_odd_even(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_even_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_even_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_first_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_first_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_odd_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_odd_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_scale_with_doc(self, *args: Any, **kwargs: Any) -> Any: ...

class XLIMEMode:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Disabled: Any
    FullAlpha: Any
    FullHangul: Any
    FullKatakana: Any
    HalfAlpha: Any
    HalfHangul: Any
    HalfKatakana: Any
    Hiragana: Any
    NoControl: Any
    Off: Any
    On: Any

def XLIconSetRule(*args: Any, **kwargs: Any) -> Any: ...
class XLImageOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    bottom_right_cell: Any
    locked: Any
    offset_x: Any
    offset_y: Any
    positioning: Any
    print_with_sheet: Any
    scale_x: Any
    scale_y: Any

class XLImagePositioning:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Absolute: Any
    OneCell: Any
    TwoCell: Any

class XLInputError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLInternalError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLLegendPosition:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Bottom: Any
    Hidden: Any
    Left: Any
    Right: Any
    Top: Any
    TopRight: Any

class XLLine:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def color(self, *args: Any, **kwargs: Any) -> Any: ...
    def style(self, *args: Any, **kwargs: Any) -> Any: ...
    def summary(self, *args: Any, **kwargs: Any) -> Any: ...

class XLLineDashType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Dash: Any
    DashDot: Any
    Dot: Any
    LgDash: Any
    LgDashDot: Any
    LgDashDotDot: Any
    Solid: Any
    SysDash: Any
    SysDashDot: Any
    SysDot: Any
    Unset: Any

class XLLineStyle:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DashDot: Any
    DashDotDot: Any
    Dashed: Any
    Dotted: Any
    Double: Any
    Hair: Any
    Medium: Any
    MediumDashDot: Any
    MediumDashDotDot: Any
    MediumDashed: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    SlantDashDot: Any
    Thick: Any
    Thin: Any

class XLMarkerStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Circle: Any
    Dash: Any
    Default: Any
    Diamond: Any
    Dot: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    Picture: Any
    Plus: Any
    Square: Any
    Star: Any
    Triangle: Any
    X: Any

class XLMergeCells:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def append_merge(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_merge(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_merge(self, *args: Any, **kwargs: Any) -> Any: ...
    def merge_exists(self, *args: Any, **kwargs: Any) -> Any: ...

def XLNotContainsBlanksRule(*args: Any, **kwargs: Any) -> Any: ...
def XLNotContainsErrorsRule(*args: Any, **kwargs: Any) -> Any: ...
def XLNotContainsTextRule(*args: Any, **kwargs: Any) -> Any: ...
class XLNumberFormat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format_code(self, *args: Any, **kwargs: Any) -> Any: ...
    def number_format_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_format_code(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_number_format_id(self, *args: Any, **kwargs: Any) -> Any: ...

class XLNumberFormats:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def number_format_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def number_format_by_index(self, *args: Any, **kwargs: Any) -> Any: ...

class XLNumberFormatter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def format(self, *args: Any, **kwargs: Any) -> Any: ...

class XLOverflowError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLPageMargins:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def header(self, *args: Any, **kwargs: Any) -> Any: ...
    def left(self, *args: Any, **kwargs: Any) -> Any: ...
    def right(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_bottom(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_header(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_left(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_right(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_top(self, *args: Any, **kwargs: Any) -> Any: ...
    def top(self, *args: Any, **kwargs: Any) -> Any: ...

class XLPageOrientation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Default: Any
    Landscape: Any
    Portrait: Any

class XLPageSetup:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def black_and_white(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_page_number(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit_to_height(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit_to_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def orientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def page_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def paper_size(self, *args: Any, **kwargs: Any) -> Any: ...
    def scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_black_and_white(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_first_page_number(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_fit_to_height(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_fit_to_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_orientation(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_page_order(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_paper_size(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_scale(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_use_first_page_number(self, *args: Any, **kwargs: Any) -> Any: ...
    def use_first_page_number(self, *args: Any, **kwargs: Any) -> Any: ...

class XLPane:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    BottomLeft: Any
    BottomRight: Any
    TopLeft: Any
    TopRight: Any

class XLPaneState:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Frozen: Any
    FrozenSplit: Any
    Split: Any

class XLPatternType:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    DarkDown: Any
    DarkGray: Any
    DarkGrid: Any
    DarkHorizontal: Any
    DarkTrellis: Any
    DarkUp: Any
    DarkVertical: Any
    Gray0625: Any
    Gray125: Any
    LightDown: Any
    LightGray: Any
    LightGrid: Any
    LightHorizontal: Any
    LightTrellis: Any
    LightUp: Any
    LightVertical: Any
    MediumGray: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    Solid: Any

class XLPerson:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    display_name: Any
    id: Any
    valid: Any

class XLPersons:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_person(self, *args: Any, **kwargs: Any) -> Any: ...
    def person(self, *args: Any, **kwargs: Any) -> Any: ...

class XLPivotField:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    custom_name: Any
    name: Any
    num_fmt_id: Any
    subtotal: Any

class XLPivotSubtotal:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Average: Any
    Count: Any
    Max: Any
    Min: Any
    Product: Any
    Sum: Any

class XLPivotTable:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def source_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def target_cell(self, *args: Any, **kwargs: Any) -> Any: ...

class XLPivotTableOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_column_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_data_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_filter_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_row_field(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_col_grand_totals(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_compact_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_data_on_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_merge_item(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_page_over_then_down(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_pivot_table_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row_grand_totals(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_col_headers(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_col_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_drill(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_error(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_last_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_row_headers(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_row_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_use_auto_formatting(self, *args: Any, **kwargs: Any) -> Any: ...

class XLPrintOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def grid_lines(self, *args: Any, **kwargs: Any) -> Any: ...
    def headings(self, *args: Any, **kwargs: Any) -> Any: ...
    def horizontal_centered(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_grid_lines(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_headings(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_horizontal_centered(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_vertical_centered(self, *args: Any, **kwargs: Any) -> Any: ...
    def vertical_centered(self, *args: Any, **kwargs: Any) -> Any: ...

class XLProperties:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def delete_property(self, *args: Any, **kwargs: Any) -> Any: ...
    def property(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_property(self, *args: Any, **kwargs: Any) -> Any: ...

class XLProperty:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    AppVersion: Any
    Application: Any
    Category: Any
    Company: Any
    CreationDate: Any
    Creator: Any
    Description: Any
    DocSecurity: Any
    HyperlinkBase: Any
    HyperlinksChanged: Any
    Keywords: Any
    LastModifiedBy: Any
    LastPrinted: Any
    LinksUpToDate: Any
    Manager: Any
    ModificationDate: Any
    ScaleCrop: Any
    SharedDoc: Any
    Subject: Any
    Title: Any

class XLPropertyError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLRelationshipItem:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def id(self, *args: Any, **kwargs: Any) -> Any: ...
    def target(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLRelationshipType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CalculationChain: Any
    Chart: Any
    ChartColorStyle: Any
    ChartStyle: Any
    Chartsheet: Any
    Comments: Any
    ControlProperties: Any
    CoreProperties: Any
    CustomProperties: Any
    Dialogsheet: Any
    Drawing: Any
    ExtendedProperties: Any
    ExternalLink: Any
    ExternalLinkPath: Any
    Hyperlink: Any
    Image: Any
    Macrosheet: Any
    Person: Any
    PivotCacheDefinition: Any
    PivotCacheRecords: Any
    PivotTable: Any
    PrinterSettings: Any
    SharedStrings: Any
    Slicer: Any
    SlicerCache: Any
    Styles: Any
    Table: Any
    Theme: Any
    ThreadedComments: Any
    Unknown: Any
    VBAProject: Any
    VMLDrawing: Any
    Workbook: Any
    Worksheet: Any

class XLRelationships:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_relationship(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_relationship(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_relationship_item(self, *args: Any, **kwargs: Any) -> Any: ...
    def id_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def relationship_by_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def relationship_by_target(self, *args: Any, **kwargs: Any) -> Any: ...
    def relationships(self, *args: Any, **kwargs: Any) -> Any: ...
    def target_exists(self, *args: Any, **kwargs: Any) -> Any: ...

class XLRichText:
    plain_text: Any
    def text(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_run(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_runs(self, *args: Any, **kwargs: Any) -> Any: ...

class XLRichTextRun:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    bold: Any
    font_color: Any
    font_name: Any
    font_size: Any
    italic: Any
    strikethrough: Any
    text: Any
    underline: Any

class XLRow:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cell_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def descent(self, *args: Any, **kwargs: Any) -> Any: ...
    def empty(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def format(self, *args: Any, **kwargs: Any) -> Any: ...
    def height(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_collapsed(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def outline_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def row_number(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_collapsed(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_descent(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_height(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_outline_level(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_values(self, *args: Any, **kwargs: Any) -> Any: ...
    def values(self, *args: Any, **kwargs: Any) -> Any: ...

class XLRowRange:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def row_count(self, *args: Any, **kwargs: Any) -> Any: ...

class XLShape:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def allow_in_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def client_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def fill_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_allow_in_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_fill_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_stroked(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style_obj(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def shape_id(self, *args: Any, **kwargs: Any) -> Any: ...
    def stroked(self, *args: Any, **kwargs: Any) -> Any: ...
    def style(self, *args: Any, **kwargs: Any) -> Any: ...
    def type(self, *args: Any, **kwargs: Any) -> Any: ...

class XLShapeClientData:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def anchor(self, *args: Any, **kwargs: Any) -> Any: ...
    def auto_fill(self, *args: Any, **kwargs: Any) -> Any: ...
    def column(self, *args: Any, **kwargs: Any) -> Any: ...
    def move_with_cells(self, *args: Any, **kwargs: Any) -> Any: ...
    def object_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_anchor(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_auto_fill(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_move_with_cells(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_object_type(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_size_with_cells(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_text_h_align(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_text_v_align(self, *args: Any, **kwargs: Any) -> Any: ...
    def size_with_cells(self, *args: Any, **kwargs: Any) -> Any: ...
    def text_h_align(self, *args: Any, **kwargs: Any) -> Any: ...
    def text_v_align(self, *args: Any, **kwargs: Any) -> Any: ...

class XLShapeStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def height(self, *args: Any, **kwargs: Any) -> Any: ...
    def hidden(self, *args: Any, **kwargs: Any) -> Any: ...
    def hide(self, *args: Any, **kwargs: Any) -> Any: ...
    def margin_left(self, *args: Any, **kwargs: Any) -> Any: ...
    def margin_top(self, *args: Any, **kwargs: Any) -> Any: ...
    def mso_wrap_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def position(self, *args: Any, **kwargs: Any) -> Any: ...
    def raw(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_height(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_margin_left(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_margin_top(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_mso_wrap_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_raw(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_v_text_anchor(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_width(self, *args: Any, **kwargs: Any) -> Any: ...
    def show(self, *args: Any, **kwargs: Any) -> Any: ...
    def v_text_anchor(self, *args: Any, **kwargs: Any) -> Any: ...
    def visible(self, *args: Any, **kwargs: Any) -> Any: ...
    def width(self, *args: Any, **kwargs: Any) -> Any: ...

class XLShapeTextHAlign:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Center: Any
    Invalid: Any
    Left: Any
    Right: Any

class XLShapeTextVAlign:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Bottom: Any
    Center: Any
    Invalid: Any
    Top: Any

class XLSheet:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def as_chartsheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def as_worksheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def color(self, *args: Any, **kwargs: Any) -> Any: ...
    def index(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_chartsheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_selected(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_worksheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_color(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_selected(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_visibility(self, *args: Any, **kwargs: Any) -> Any: ...
    def visibility(self, *args: Any, **kwargs: Any) -> Any: ...

class XLSheetError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLSheetProtectionOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    auto_filter: Any
    delete_columns: Any
    delete_rows: Any
    format_cells: Any
    format_columns: Any
    format_rows: Any
    insert_columns: Any
    insert_hyperlinks: Any
    insert_rows: Any
    objects: Any
    pivot_tables: Any
    scenarios: Any
    select_locked_cells: Any
    select_unlocked_cells: Any
    sheet: Any
    sort: Any

class XLSheetState:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Hidden: Any
    VeryHidden: Any
    Visible: Any

class XLSheetType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Chartsheet: Any
    Dialogsheet: Any
    Macrosheet: Any
    Worksheet: Any

class XLSlicer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def move_to(self, *args: Any, **kwargs: Any) -> Any: ...
    def resize(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_caption(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style_raw(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_all(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_only(self, *args: Any, **kwargs: Any) -> Any: ...

class XLSlicerBuilder:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def build(self, *args: Any, **kwargs: Any) -> Any: ...
    def caption(self, *args: Any, **kwargs: Any) -> Any: ...
    def column_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def locked_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def offset(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_only(self, *args: Any, **kwargs: Any) -> Any: ...
    def size(self, *args: Any, **kwargs: Any) -> Any: ...
    def sort_descending(self, *args: Any, **kwargs: Any) -> Any: ...
    def style(self, *args: Any, **kwargs: Any) -> Any: ...
    def style_raw(self, *args: Any, **kwargs: Any) -> Any: ...

class XLSlicerCollection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_pivot(self, *args: Any, **kwargs: Any) -> Any: ...
    def contains(self, *args: Any, **kwargs: Any) -> Any: ...
    def find(self, *args: Any, **kwargs: Any) -> Any: ...
    def remove(self, *args: Any, **kwargs: Any) -> Any: ...

class XLSlicerOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    caption: Any
    height: Any
    name: Any
    offset_x: Any
    offset_y: Any
    width: Any

class XLSlicerStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Custom: Any
    Dark1: Any
    Dark2: Any
    Dark3: Any
    Dark4: Any
    Dark5: Any
    Dark6: Any
    Light1: Any
    Light2: Any
    Light3: Any
    Light4: Any
    Light5: Any
    Light6: Any
    Other1: Any
    Other2: Any

class XLSparklineOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    display_empty_cells_as: Any
    display_x_axis: Any
    first: Any
    first_marker_color: Any
    high: Any
    high_marker_color: Any
    last: Any
    last_marker_color: Any
    low: Any
    low_marker_color: Any
    markers: Any
    markers_color: Any
    negative: Any
    negative_color: Any
    series_color: Any
    type: Any

class XLSparklineType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Column: Any
    Line: Any
    Stacked: Any

class XLStreamEmptyRowPolicy:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    EmitEmptyRows: Any
    SkipMissingRows: Any

class XLStreamReadOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    apply_number_formats: Any
    empty_rows: Any

class XLStreamReader:
    current_row_index: Any
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> XLStreamReader: ...
    def __exit__(self, *args: Any) -> Any: ...
    def close(self, *args: Any, **kwargs: Any) -> Any: ...
    def current_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def current_row_opts(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_next(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_row_detailed(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_row_strings(self, *args: Any, **kwargs: Any) -> Any: ...

class XLStreamRowOpts:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    height: Any
    hidden: Any
    outline_level: Any
    style_index: Any

class XLStreamWriter:
    is_active: Any
    last_row: Any
    max_column: Any
    def write_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __enter__(self) -> XLStreamWriter: ...
    def __exit__(self, *args: Any) -> Any: ...
    def append_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def append_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self, *args: Any, **kwargs: Any) -> Any: ...
    def flush(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_stream_active(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_row_ref(self, *args: Any, **kwargs: Any) -> Any: ...

class XLStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Alignment: Any
    Border: Any
    BorderElement: Any
    Fill: Any
    Font: Any
    alignment: Any
    border: Any
    fill: Any
    font: Any
    number_format: Any

class XLStyles:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def borders(self, *args: Any, **kwargs: Any) -> Any: ...
    def cell_formats(self, *args: Any, **kwargs: Any) -> Any: ...
    def fills(self, *args: Any, **kwargs: Any) -> Any: ...
    def fonts(self, *args: Any, **kwargs: Any) -> Any: ...
    def number_formats(self, *args: Any, **kwargs: Any) -> Any: ...

class XLTable:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def append_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def column(self, *args: Any, **kwargs: Any) -> Any: ...
    def comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def display_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def range_reference(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_display_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_range_reference(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_column_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_first_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_header_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_last_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_row_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_show_totals_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_style_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_column_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_first_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_header_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_last_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_row_stripes(self, *args: Any, **kwargs: Any) -> Any: ...
    def show_totals_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def style_name(self, *args: Any, **kwargs: Any) -> Any: ...

class XLTableColumn:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculated_column_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def id(self, *args: Any, **kwargs: Any) -> Any: ...
    def name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_calculated_column_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_totals_row_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_totals_row_function(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_totals_row_label(self, *args: Any, **kwargs: Any) -> Any: ...
    def totals_row_formula(self, *args: Any, **kwargs: Any) -> Any: ...
    def totals_row_function(self, *args: Any, **kwargs: Any) -> Any: ...
    def totals_row_label(self, *args: Any, **kwargs: Any) -> Any: ...

class XLTables:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_range(self, *args: Any, **kwargs: Any) -> Any: ...
    def count(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_table(self, *args: Any, **kwargs: Any) -> Any: ...

class XLThreadedComment:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    id: Any
    is_resolved: Any
    parent_id: Any
    person_id: Any
    ref: Any
    text: Any
    valid: Any

class XLThreadedComments:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_reply(self, *args: Any, **kwargs: Any) -> Any: ...
    def comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def replies(self, *args: Any, **kwargs: Any) -> Any: ...

def XLTop10Rule(*args: Any, **kwargs: Any) -> Any: ...
class XLTotalsRowFunction:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Average: Any
    Count: Any
    CountNums: Any
    Custom: Any
    Max: Any
    Min: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    StdDev: Any
    Sum: Any
    Var: Any

class XLTrendlineType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Exponential: Any
    Linear: Any
    Logarithmic: Any
    MovingAverage: Any
    Polynomial: Any
    Power: Any

class XLUnderlineStyle:
    __members__: dict[str, Any]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Double: Any
    # Runtime member name is the keyword None; use getattr(Cls, 'None')
    Single: Any

class XLValueTypeError(XLException):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class XLVectorShapeOptions:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    arrow_end: Any
    arrow_start: Any
    end_col: Any
    end_offset_x: Any
    end_offset_y: Any
    end_row: Any
    fill_color: Any
    flip_h: Any
    flip_v: Any
    height: Any
    horz_align: Any
    line_color: Any
    line_dash: Any
    line_width: Any
    macro: Any
    name: Any
    offset_x: Any
    offset_y: Any
    rich_text: Any
    rotation: Any
    text: Any
    type: Any
    vert_align: Any
    width: Any

class XLVectorShapeType:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Arrow: Any
    Cloud: Any
    Diamond: Any
    Donut: Any
    Ellipse: Any
    FlowChartData: Any
    FlowChartDecision: Any
    FlowChartDocument: Any
    FlowChartProcess: Any
    Heart: Any
    Hexagon: Any
    LightningBolt: Any
    Line: Any
    Moon: Any
    Parallelogram: Any
    Rectangle: Any
    Ribbon: Any
    RightTriangle: Any
    SmileyFace: Any
    Star16: Any
    Star24: Any
    Star4: Any
    Star5: Any
    Sun: Any
    Triangle: Any

class XLVerticalAlignRunStyle:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    Baseline: Any
    Subscript: Any
    Superscript: Any

class XLVmlDrawing:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_shape(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_shape(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_shape_by_ref(self, *args: Any, **kwargs: Any) -> Any: ...
    def shape(self, *args: Any, **kwargs: Any) -> Any: ...
    def shape_count(self, *args: Any, **kwargs: Any) -> Any: ...

class XLWorkbook:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_chartsheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_worksheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def chartsheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def chartsheet_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def chartsheet_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def chartsheet_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_active_tab(self, *args: Any, **kwargs: Any) -> Any: ...
    def clone_sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def defined_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_named_ranges(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def index_of_sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_protected(self, *args: Any, **kwargs: Any) -> Any: ...
    def protect(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_full_calculation_on_load(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_sheet_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def sheet_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def type_of_sheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def unprotect(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_sheet_references(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_worksheet_dimensions(self, *args: Any, **kwargs: Any) -> Any: ...
    def worksheet(self, *args: Any, **kwargs: Any) -> Any: ...
    def worksheet_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def worksheet_exists(self, *args: Any, **kwargs: Any) -> Any: ...
    def worksheet_names(self, *args: Any, **kwargs: Any) -> Any: ...

class XLWorksheet:
    def sheet_protected(self, *args: Any, **kwargs: Any) -> Any: ...
    def password_is_set(self, *args: Any, **kwargs: Any) -> Any: ...
    def objects_protected(self, *args: Any, **kwargs: Any) -> Any: ...
    def scenarios_protected(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_rows_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_locked_cells_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def select_unlocked_cells_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def sort_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def pivot_tables_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_chart(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_chart_anchor(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_conditional_formatting(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_conditional_formatting_dxf(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_hyperlink(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_internal_hyperlink(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_note(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_pivot_slicer(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_pivot_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_reply(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_scaled_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_shape(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_sort_condition(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_sparkline(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_table_slicer(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_threaded_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_threaded_reply(self, *args: Any, **kwargs: Any) -> Any: ...
    def append_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def apply_auto_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def auto_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def auto_filter_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def auto_fit_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def autofilter_object(self, *args: Any, **kwargs: Any) -> Any: ...
    def cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_all_conditional_formatting(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_auto_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_panes(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_password(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_sheet_protection(self, *args: Any, **kwargs: Any) -> Any: ...
    def column(self, *args: Any, **kwargs: Any) -> Any: ...
    def column_count(self, *args: Any, **kwargs: Any) -> Any: ...
    def column_format(self, *args: Any, **kwargs: Any) -> Any: ...
    def comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def conditional_formats(self, *args: Any, **kwargs: Any) -> Any: ...
    def data_validations(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_columns_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_comment(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_note(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_pivot_table(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_rows_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_slicer(self, *args: Any, **kwargs: Any) -> Any: ...
    def drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_cell(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit_to_pages(self, *args: Any, **kwargs: Any) -> Any: ...
    def format_cells_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def format_columns_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def format_rows_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def freeze_panes(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_cell_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_hyperlink(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_range_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_range_values(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_row_values(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_rows_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def group_columns(self, *args: Any, **kwargs: Any) -> Any: ...
    def group_rows(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_auto_filter(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_hyperlink(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_panes(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_relationships(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_tables(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_threaded_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def has_vml_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
    def header_footer(self, *args: Any, **kwargs: Any) -> Any: ...
    def images(self, *args: Any, **kwargs: Any) -> Any: ...
    def index(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_col_break(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_column(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_columns_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_hyperlinks_allowed(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_image(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_image_bytes(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_image_opt(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_row(self, *args: Any, **kwargs: Any) -> Any: ...
    def insert_row_break(self, *args: Any, **kwargs: Any) -> Any: ...
    # ...

    def threaded_comments(self, *args: Any, **kwargs: Any) -> Any: ...
    def vml_drawing(self, *args: Any, **kwargs: Any) -> Any: ...
def create_pivot_options(*args: Any, **kwargs: Any) -> Any: ...
def init_random(*args: Any, **kwargs: Any) -> Any: ...
def use_random_ids(*args: Any, **kwargs: Any) -> Any: ...
def use_sequential_ids(*args: Any, **kwargs: Any) -> Any: ...