from enum import Enum
from typing import Any, List, Union, overload, Iterator
import datetime

class XLContentType(Enum):
    Workbook: int
    Relationships: int
    WorkbookMacroEnabled: int
    Worksheet: int
    Chartsheet: int
    ExternalLink: int
    Theme: int
    Styles: int
    SharedStrings: int
    Drawing: int
    Chart: int
    ChartStyle: int
    ChartColorStyle: int
    ControlProperties: int
    CalculationChain: int
    VBAProject: int
    CoreProperties: int
    ExtendedProperties: int
    CustomProperties: int
    Comments: int
    Table: int
    VMLDrawing: int
    Unknown: int

class XLProperty(Enum):
    Title: int
    Subject: int
    Creator: int
    Keywords: int
    Description: int
    LastModifiedBy: int
    LastPrinted: int
    CreationDate: int
    ModificationDate: int
    Category: int
    Application: int
    DocSecurity: int
    ScaleCrop: int
    Manager: int
    Company: int
    LinksUpToDate: int
    SharedDoc: int
    HyperlinkBase: int
    HyperlinksChanged: int
    AppVersion: int

class XLSheetState(Enum):
    Visible: int
    Hidden: int
    VeryHidden: int

class XLUnderlineStyle(Enum):
    None_: int
    Single: int
    Double: int

class XLFontSchemeStyle(Enum):
    None_: int
    Major: int
    Minor: int

class XLVerticalAlignRunStyle(Enum):
    Baseline: int
    Subscript: int
    Superscript: int

class XLFillType(Enum):
    Gradient: int
    Pattern: int

class XLPatternType(Enum):
    None_: int
    Solid: int
    MediumGray: int
    DarkGray: int
    LightGray: int
    DarkHorizontal: int
    DarkVertical: int
    DarkDown: int
    DarkUp: int
    DarkGrid: int
    DarkTrellis: int
    LightHorizontal: int
    LightVertical: int
    LightDown: int
    LightUp: int
    LightGrid: int
    LightTrellis: int
    Gray125: int
    Gray0625: int

class XLLineStyle(Enum):
    None_: int
    Thin: int
    Medium: int
    Dashed: int
    Dotted: int
    Thick: int
    Double: int
    Hair: int
    MediumDashed: int
    DashDot: int
    MediumDashDot: int
    DashDotDot: int
    MediumDashDotDot: int
    SlantDashDot: int

class XLAlignmentStyle(Enum):
    General: int
    Left: int
    Right: int
    Center: int
    Top: int
    Bottom: int
    Fill: int
    Justify: int
    CenterContinuous: int
    Distributed: int

class XLContentItem:
    def __init__(self) -> None: ...
    def type(self) -> XLContentType: ...
    def path(self) -> str: ...

class XLContentTypes:
    def add_override(self, path: str, type: Union[XLContentType, int]) -> None: ...
    @overload
    def delete_override(self, path: str) -> None: ...
    @overload
    def delete_override(self, item: XLContentItem) -> None: ...
    def content_item(self, path: str) -> XLContentItem: ...
    def get_content_items(self) -> List[XLContentItem]: ...

class XLComment:
    def valid(self) -> bool: ...
    def ref(self) -> str: ...
    def text(self) -> str: ...
    def author_id(self) -> int: ...
    def set_text(self, text: str) -> None: ...
    def set_author_id(self, id: int) -> None: ...

class XLShapeStyle:
    def width(self) -> int: ...
    def height(self) -> int: ...
    def set_width(self, width: int) -> None: ...
    def set_height(self, height: int) -> None: ...
    def set_raw(self, name: str, value: str) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...

class XLShapeClientData:
    def auto_fill(self) -> bool: ...
    def set_auto_fill(self, auto_fill: bool) -> None: ...
    def set_anchor(self, anchor: str) -> None: ...

class XLShape:
    def style(self) -> XLShapeStyle: ...
    def client_data(self) -> XLShapeClientData: ...

class XLComments:
    def count(self) -> int: ...
    @overload
    def get(self, index: int) -> XLComment: ...
    @overload
    def get(self, cellRef: str) -> XLComment: ...
    def set(self, cellRef: str, comment: str, author_id: int = 0) -> None: ...
    def shape(self, cellRef: str) -> XLShape: ...
    def delete_comment(self, cellRef: str) -> None: ...
    def author_count(self) -> int: ...
    def author(self, index: int) -> str: ...
    def add_author(self, name: str) -> None: ...

class XLDateTime:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, serial: float) -> None: ...
    @overload
    def __init__(self, timestamp: int) -> None: ...
    def serial(self) -> float: ...
    def as_datetime(self) -> datetime.datetime: ...

class XLColor:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, r: int, g: int, b: int, a: int) -> None: ...
    @overload
    def __init__(self, r: int, g: int, b: int) -> None: ...
    @overload
    def __init__(self, hex: str) -> None: ...
    @overload
    def set(self, r: int, g: int, b: int, a: int) -> None: ...
    @overload
    def set(self, r: int, g: int, b: int) -> None: ...
    @overload
    def set(self, hex: str) -> None: ...
    def alpha(self) -> int: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def hex(self) -> str: ...

class XLFont:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def size(self) -> int: ...
    def set_size(self, size: int) -> None: ...
    def color(self) -> XLColor: ...
    def set_color(self, color: XLColor) -> None: ...
    def bold(self) -> bool: ...
    def set_bold(self, set: bool = True) -> None: ...
    def italic(self) -> bool: ...
    def set_italic(self, set: bool = True) -> None: ...
    def strikethrough(self) -> bool: ...
    def set_strikethrough(self, set: bool = True) -> None: ...
    def underline(self) -> XLUnderlineStyle: ...
    def set_underline(self, style: Union[XLUnderlineStyle, int] = ...) -> None: ...
    def scheme(self) -> XLFontSchemeStyle: ...
    def set_scheme(self, style: XLFontSchemeStyle) -> None: ...
    def vert_align(self) -> XLVerticalAlignRunStyle: ...
    def set_vert_align(self, style: XLVerticalAlignRunStyle) -> None: ...

class XLFill:
    def __init__(self) -> None: ...
    def fill_type(self) -> XLFillType: ...
    def set_fill_type(self, newFillType: XLFillType, force: bool = False) -> None: ...
    def pattern_type(self) -> XLPatternType: ...
    def set_pattern_type(self, type: XLPatternType) -> None: ...
    def color(self) -> XLColor: ...
    def set_color(self, color: XLColor) -> None: ...
    def background_color(self) -> XLColor: ...
    def set_background_color(self, color: XLColor) -> None: ...

class XLLine:
    def __init__(self) -> None: ...
    def style(self) -> XLLineStyle: ...
    def color(self) -> XLColor: ...
    def __bool__(self) -> bool: ...

class XLBorder:
    def __init__(self) -> None: ...
    def left(self) -> XLLine: ...
    def right(self) -> XLLine: ...
    def top(self) -> XLLine: ...
    def bottom(self) -> XLLine: ...
    def diagonal(self) -> XLLine: ...
    def set_left(
        self, lineStyle: XLLineStyle, lineColor: XLColor, lineTint: float = 0.0
    ) -> None: ...
    def set_right(
        self, lineStyle: XLLineStyle, lineColor: XLColor, lineTint: float = 0.0
    ) -> None: ...
    def set_top(
        self, lineStyle: XLLineStyle, lineColor: XLColor, lineTint: float = 0.0
    ) -> None: ...
    def set_bottom(
        self, lineStyle: XLLineStyle, lineColor: XLColor, lineTint: float = 0.0
    ) -> None: ...
    def set_diagonal(
        self, lineStyle: XLLineStyle, lineColor: XLColor, lineTint: float = 0.0
    ) -> None: ...

class XLAlignment:
    def __init__(self) -> None: ...
    def horizontal(self) -> XLAlignmentStyle: ...
    def set_horizontal(self, style: XLAlignmentStyle) -> None: ...
    def vertical(self) -> XLAlignmentStyle: ...
    def set_vertical(self, style: XLAlignmentStyle) -> None: ...
    def rotation(self) -> int: ...
    def set_rotation(self, rotation: int) -> None: ...
    def wrap_text(self) -> bool: ...
    def set_wrap_text(self, set: bool = True) -> None: ...
    def indent(self) -> int: ...
    def set_indent(self, indent: int) -> None: ...
    def shrink_to_fit(self) -> bool: ...
    def set_shrink_to_fit(self, set: bool = True) -> None: ...

class XLCellFormat:
    def __init__(self) -> None: ...
    def font_index(self) -> int: ...
    def set_font_index(self, index: int) -> None: ...
    def fill_index(self) -> int: ...
    def set_fill_index(self, index: int) -> None: ...
    def border_index(self) -> int: ...
    def set_border_index(self, index: int) -> None: ...
    def number_format_id(self) -> int: ...
    def set_number_format_id(self, id: int) -> None: ...
    def apply_number_format(self) -> bool: ...
    def set_apply_number_format(self, set: bool = True) -> None: ...
    def alignment(self, createIfMissing: bool = False) -> XLAlignment: ...
    def apply_font(self) -> bool: ...
    def set_apply_font(self, set: bool = True) -> None: ...
    def apply_fill(self) -> bool: ...
    def set_apply_fill(self, set: bool = True) -> None: ...
    def apply_border(self) -> bool: ...
    def set_apply_border(self, set: bool = True) -> None: ...
    def apply_alignment(self) -> bool: ...
    def set_apply_alignment(self, set: bool = True) -> None: ...
    def locked(self) -> bool: ...
    def set_locked(self, set: bool = True) -> None: ...
    def hidden(self) -> bool: ...
    def set_hidden(self, set: bool = True) -> None: ...
    def apply_protection(self) -> bool: ...
    def set_apply_protection(self, set: bool = True) -> None: ...

class XLFonts:
    def count(self) -> int: ...
    def font_by_index(self, index: int) -> XLFont: ...
    def __getitem__(self, index: int) -> XLFont: ...
    def create(self, copyFrom: XLFont = ..., styleEntriesPrefix: str = ...) -> int: ...

class XLFills:
    def count(self) -> int: ...
    def fill_by_index(self, index: int) -> XLFill: ...
    def __getitem__(self, index: int) -> XLFill: ...
    def create(self, copyFrom: XLFill = ..., styleEntriesPrefix: str = ...) -> int: ...

class XLBorders:
    def count(self) -> int: ...
    def border_by_index(self, index: int) -> XLBorder: ...
    def __getitem__(self, index: int) -> XLBorder: ...
    def create(
        self, copyFrom: XLBorder = ..., styleEntriesPrefix: str = ...
    ) -> int: ...

class XLCellFormats:
    def count(self) -> int: ...
    def cell_format_by_index(self, index: int) -> XLCellFormat: ...
    def __getitem__(self, index: int) -> XLCellFormat: ...
    def create(
        self, copyFrom: XLCellFormat = ..., styleEntriesPrefix: str = ...
    ) -> int: ...

class XLNumberFormat:
    def __init__(self) -> None: ...
    def number_format_id(self) -> int: ...
    def set_number_format_id(self, id: int) -> None: ...
    def format_code(self) -> str: ...
    def set_format_code(self, code: str) -> None: ...

class XLNumberFormats:
    def count(self) -> int: ...
    def number_format_by_index(self, index: int) -> XLNumberFormat: ...
    def number_format_by_id(self, id: int) -> XLNumberFormat: ...
    def __getitem__(self, index: int) -> XLNumberFormat: ...
    def create(
        self, copyFrom: XLNumberFormat = ..., styleEntriesPrefix: str = ...
    ) -> int: ...

class XLStyles:
    def fonts(self) -> XLFonts: ...
    def fills(self) -> XLFills: ...
    def borders(self) -> XLBorders: ...
    def cell_formats(self) -> XLCellFormats: ...
    def number_formats(self) -> XLNumberFormats: ...

class ImageInfo:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def extension(self) -> str: ...

class XLProperties:
    @overload
    def set_property(self, name: str, value: str) -> None: ...
    @overload
    def set_property(self, name: str, value: int) -> None: ...
    @overload
    def set_property(self, name: str, value: float) -> None: ...
    def property(self, name: str) -> str: ...
    def delete_property(self, name: str) -> None: ...

class XLAppProperties:
    def increment_sheet_count(self, increment: int) -> None: ...
    def align_worksheets(self, names: List[str]) -> None: ...
    def add_sheet_name(self, title: str) -> None: ...
    def delete_sheet_name(self, title: str) -> None: ...
    def set_sheet_name(self, oldTitle: str, newTitle: str) -> None: ...
    def add_heading_pair(self, name: str, value: int) -> None: ...
    def delete_heading_pair(self, name: str) -> None: ...
    def set_heading_pair(self, name: str, newValue: int) -> None: ...
    def set_property(self, name: str, value: str) -> None: ...
    def property(self, name: str) -> str: ...
    def delete_property(self, name: str) -> None: ...
    def append_sheet_name(self, name: str) -> None: ...
    def prepend_sheet_name(self, name: str) -> None: ...
    def insert_sheet_name(self, name: str, index: int) -> None: ...

class XLWorkbook:
    def worksheet(self, name: str) -> XLWorksheet: ...
    def add_worksheet(self, name: str) -> XLWorksheet: ...
    def delete_sheet(self, name: str) -> None: ...
    def clone_sheet(self, existingName: str, newName: str) -> None: ...
    def sheet_count(self) -> int: ...
    def worksheet_names(self) -> List[str]: ...
    def sheet_exists(self, name: str) -> bool: ...
    def clear_active_tab(self) -> None: ...

class RowValuesIterator:
    def __iter__(self) -> RowValuesIterator: ...
    def __next__(self) -> List[Any]: ...

class XLWorksheet:
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def index(self) -> int: ...
    def set_index(self, index: int) -> None: ...
    def visibility(self) -> XLSheetState: ...
    def set_visibility(self, state: XLSheetState) -> None: ...
    def is_active(self) -> bool: ...
    def set_active(self) -> None: ...
    def row_count(self) -> int: ...
    def column_count(self) -> int: ...
    @overload
    def cell(self, ref: str) -> XLCell: ...
    @overload
    def cell(self, row: int, col: int) -> XLCell: ...
    @overload
    def range(self, address: str) -> XLCellRange: ...
    @overload
    def range(self, topLeft: str, bottomRight: str) -> XLCellRange: ...
    @overload
    def column(self, index: int) -> XLColumn: ...
    @overload
    def column(self, name: str) -> XLColumn: ...
    def merge_cells(
        self, rangeReference: str, emptyHiddenCells: bool = False
    ) -> None: ...
    def unmerge_cells(self, rangeReference: str) -> None: ...
    def column_format(self, column: str) -> int: ...
    def merges(self) -> XLMergeCells: ...
    @overload
    def set_column_format(self, column: str, cellFormatIndex: int) -> None: ...
    @overload
    def set_column_format(self, column: int, cellFormatIndex: int) -> None: ...
    def row_format(self, row: int) -> int: ...
    def set_row_format(self, row: int, cellFormatIndex: int) -> None: ...
    def protect_sheet(self, set: bool = True) -> None: ...
    def protect_objects(self, set: bool = True) -> None: ...
    def protect_scenarios(self, set: bool = True) -> None: ...
    def sheet_protected(self) -> bool: ...
    def objects_protected(self) -> bool: ...
    def scenarios_protected(self) -> bool: ...
    def set_password(self, password: str) -> None: ...
    def clear_password(self) -> None: ...
    def password_hash(self) -> str: ...
    def password_is_set(self) -> bool: ...
    def insert_columns_allowed(self) -> bool: ...
    def insert_rows_allowed(self) -> bool: ...
    def delete_columns_allowed(self) -> bool: ...
    def delete_rows_allowed(self) -> bool: ...
    def select_locked_cells_allowed(self) -> bool: ...
    def select_unlocked_cells_allowed(self) -> bool: ...
    def set_insert_columns_allowed(self, set: bool = True) -> None: ...
    def set_insert_rows_allowed(self, set: bool = True) -> None: ...
    def set_delete_columns_allowed(self, set: bool = True) -> None: ...
    def set_delete_rows_allowed(self, set: bool = True) -> None: ...
    def set_select_locked_cells_allowed(self, set: bool = True) -> None: ...
    def set_select_unlocked_cells_allowed(self, set: bool = True) -> None: ...
    def comments(self) -> XLComments: ...
    def add_image(
        self,
        image_data: bytes,
        extension: str,
        row: int,
        col: int,
        width: int,
        height: int,
    ) -> None: ...
    def get_rows_data(self) -> List[List[Any]]: ...
    def get_row_values(self, row: int) -> List[Any]: ...
    def get_range_data(
        self, start_row: int, start_col: int, end_row: int, end_col: int
    ) -> List[List[Any]]: ...
    def get_cell_value(self, row: int, col: int) -> Any: ...
    def iter_row_values(self) -> RowValuesIterator: ...
    def write_range_data(self, start_row: int, start_col: int, data: Any) -> None: ...
    def get_range_values(
        self, start_row: int, start_col: int, end_row: int, end_col: int
    ) -> Any: ...
    def set_cell_value(self, row: int, col: int, value: Any) -> None: ...
    def write_rows_data(
        self, start_row: int, start_col: int, rows: List[List[Any]]
    ) -> None: ...
    def write_row_data(self, row: int, start_col: int, values: List[Any]) -> None: ...
    def set_cells_batch(self, cells: List[tuple]) -> None: ...

class XLColumn:
    def width(self) -> float: ...
    def set_width(self, width: float) -> None: ...
    def is_hidden(self) -> bool: ...
    def set_hidden(self, state: bool) -> None: ...
    def format(self) -> int: ...
    def set_format(self, cellFormatIndex: int) -> None: ...

class XLMergeCells:
    def count(self) -> int: ...
    def find_merge(self, cellRef: str) -> str: ...
    def merge_exists(self, rangeRef: str) -> bool: ...
    def append_merge(self, rangeRef: str) -> None: ...
    def delete_merge(self, rangeRef: str) -> None: ...
    def __getitem__(self, index: int) -> str: ...

class XLCellReference:
    @overload
    def __init__(self, address: str) -> None: ...
    @overload
    def __init__(self, row: int, col: int) -> None: ...
    def address(self) -> str: ...
    def row(self) -> int: ...
    def column(self) -> int: ...

class XLCellRange:
    def address(self) -> str: ...
    def num_rows(self) -> int: ...
    def num_columns(self) -> int: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Iterator[XLCell]: ...

class XLFormula:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, formula: str) -> None: ...
    def get(self) -> str: ...
    def clear(self) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class XLCell:
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, value: Any) -> None: ...
    def get_formula(self) -> str: ...
    def set_formula(self, value: Union[str, XLFormula]) -> None: ...
    def clear_formula(self) -> None: ...
    def has_formula(self) -> bool: ...
    def cell_reference(self) -> XLCellReference: ...
    def cell_format(self) -> int: ...
    def set_cell_format(self, index: int) -> None: ...

class XLDocument:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, path: str) -> None: ...
    def open(self, path: str) -> None: ...
    def create(self, name: str, force_overwrite: bool = True) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...
    def name(self) -> str: ...
    def path(self) -> str: ...
    def save(self) -> None: ...
    def save_as(self, name: str, force_overwrite: bool = True) -> None: ...
    def workbook(self) -> XLWorkbook: ...
    def content_types(self) -> XLContentTypes: ...
    def app_properties(self) -> XLAppProperties: ...
    def core_properties(self) -> XLProperties: ...
    def property(self, property: Union[XLProperty, int]) -> str: ...
    def set_property(self, property: Union[XLProperty, int], value: str) -> None: ...
    def delete_property(self, property: Union[XLProperty, int]) -> None: ...
    def styles(self) -> XLStyles: ...
    def get_embedded_images(self) -> List[ImageInfo]: ...
    def get_image_data(self, image_path: str) -> bytes: ...
    def __enter__(self) -> XLDocument: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
