from typing import Optional, Union, Any

class FilterColumn:
    def __init__(self, raw_column: Any, autofilter: Optional['AutoFilter'] = None) -> None: ...
    @property
    def col_id(self) -> int: ...
    def add_filter(self, value: Any) -> None: ...
    def clear(self) -> None: ...
    def set_custom_filter(self, op: str, val: Any, logic: Optional[str] = None, op2: Optional[str] = None, val2: Optional[Any] = None) -> None: ...
    def set_top10(self, value: float, percent: bool = False, top: bool = True) -> None: ...

class AutoFilter:
    def __init__(self, raw_autofilter: Any, worksheet: Optional[Any] = None) -> None: ...
    def __bool__(self) -> bool: ...
    @property
    def ref(self) -> str: ...
    @ref.setter
    def ref(self, value: str) -> None: ...
    def filter_column(self, col_id: int) -> FilterColumn: ...
    def __getitem__(self, col_id: int) -> FilterColumn: ...
    def __eq__(self, other: Any) -> bool: ...
    def __str__(self) -> str: ...
