from typing import Any, Optional
from ._openxlsx import XLColumn

class Column:
    __slots__ = ("_column", "_worksheet_ref", "_workbook_ref")
    @property
    def _worksheet(self) -> Optional[Any]: ...
    @property
    def _workbook(self) -> Optional[Any]: ...
    def __init__(self, raw_column: XLColumn, worksheet: Any = None) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, value: bool) -> None: ...
    @property
    def style_index(self) -> int: ...
    @style_index.setter
    def style_index(self, value: int) -> None: ...
