from typing import Any, Optional, Sequence, Tuple, Union
from ._openxlsx import XLCfOperator, XLColor

ColorLike = Union[XLColor, Tuple[int, int, int], Sequence[int], str]

def color_scale(
    start: ColorLike,
    end: ColorLike,
    mid: Optional[ColorLike] = ...,
) -> Any: ...
def data_bar(
    color: ColorLike = ..., *, show_value: bool = ...
) -> Any: ...
def cell_is(
    operator: Union[str, XLCfOperator],
    formula: str,
    formula2: Optional[str] = ...,
) -> Any: ...
def formula_rule(formula: str) -> Any: ...
def icon_set(
    name: str = ..., *, show_value: bool = ..., reverse: bool = ...
) -> Any: ...
def top10(
    rank: int = ..., *, percent: bool = ..., bottom: bool = ...
) -> Any: ...
def above_average(
    *, above: bool = ..., equal_average: bool = ..., std_dev: int = ...
) -> Any: ...
def duplicate_values(*, unique: bool = ...) -> Any: ...
def contains_text(text: str) -> Any: ...
def not_contains_text(text: str) -> Any: ...
def contains_blanks() -> Any: ...
def not_contains_blanks() -> Any: ...
def contains_errors() -> Any: ...
def not_contains_errors() -> Any: ...
