from typing import Any, Iterator, List, Optional

class DefinedName:
    def __init__(self, native: Any) -> None: ...
    @property
    def raw(self) -> Any: ...
    def name(self) -> str: ...
    def set_name(self, value: str) -> None: ...
    def refers_to(self) -> str: ...
    def set_refers_to(self, value: str) -> None: ...
    def local_sheet_id(self) -> Optional[int]: ...
    def hidden(self) -> bool: ...
    def set_hidden(self, value: bool) -> None: ...
    def comment(self) -> str: ...
    def set_comment(self, value: str) -> None: ...
    def valid(self) -> bool: ...
    def __getattr__(self, name: str) -> Any: ...

class DefinedNames:
    def __init__(self, native: Any, workbook: Any = ...) -> None: ...
    @property
    def raw(self) -> Any: ...
    def define(
        self,
        name: str,
        refers_to: str,
        *,
        local_sheet_id: Optional[int] = ...,
        sheet: Any = ...,
        hidden: bool = ...,
        comment: str = ...,
    ) -> DefinedName: ...
    def append(
        self,
        name: str,
        formula: str,
        local_sheet_id: Optional[int] = ...,
    ) -> Any: ...
    def get(
        self, name: str, local_sheet_id: Optional[int] = ...
    ) -> DefinedName: ...
    def remove(
        self, name: str, local_sheet_id: Optional[int] = ...
    ) -> None: ...
    def exists(
        self, name: str, local_sheet_id: Optional[int] = ...
    ) -> bool: ...
    def count(self) -> int: ...
    def all(self) -> List[DefinedName]: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> DefinedName: ...
    def __iter__(self) -> Iterator[DefinedName]: ...
    def __getattr__(self, name: str) -> Any: ...
