from typing import Any
from ._openxlsx import XLCell

class Formula:
    def __init__(self, raw_cell: XLCell) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    def clear(self) -> None: ...
