from typing import Iterator, Union
from ._openxlsx import XLMergeCells

class MergeCells:
    def __init__(self, raw_merges: XLMergeCells) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, item: str) -> bool: ...
    def append(self, reference: str) -> None: ...
    def delete(self, index: int) -> None: ...
    def find(self, reference: str) -> int: ...
