from typing import Any

class PageMargins:
    def __init__(self, raw_margins: Any, worksheet: Any = None) -> None: ...
    @property
    def left(self) -> float: ...
    @left.setter
    def left(self, value: float) -> None: ...
    @property
    def right(self) -> float: ...
    @right.setter
    def right(self, value: float) -> None: ...
    @property
    def top(self) -> float: ...
    @top.setter
    def top(self, value: float) -> None: ...
    @property
    def bottom(self) -> float: ...
    @bottom.setter
    def bottom(self, value: float) -> None: ...
    @property
    def header(self) -> float: ...
    @header.setter
    def header(self, value: float) -> None: ...
    @property
    def footer(self) -> float: ...
    @footer.setter
    def footer(self, value: float) -> None: ...

class PrintOptions:
    def __init__(self, raw_options: Any, worksheet: Any = None) -> None: ...
    @property
    def grid_lines(self) -> bool: ...
    @grid_lines.setter
    def grid_lines(self, value: bool) -> None: ...
    @property
    def headings(self) -> bool: ...
    @headings.setter
    def headings(self, value: bool) -> None: ...
    @property
    def horizontal_centered(self) -> bool: ...
    @horizontal_centered.setter
    def horizontal_centered(self, value: bool) -> None: ...
    @property
    def vertical_centered(self) -> bool: ...
    @vertical_centered.setter
    def vertical_centered(self, value: bool) -> None: ...

class PageSetup:
    def __init__(self, raw_setup: Any, worksheet: Any = None) -> None: ...
    @property
    def paper_size(self) -> int: ...
    @paper_size.setter
    def paper_size(self, value: int) -> None: ...
    @property
    def orientation(self) -> Any: ...
    @orientation.setter
    def orientation(self, value: Any) -> None: ...
    @property
    def scale(self) -> int: ...
    @scale.setter
    def scale(self, value: int) -> None: ...
    @property
    def fit_to_width(self) -> int: ...
    @fit_to_width.setter
    def fit_to_width(self, value: int) -> None: ...
    @property
    def fit_to_height(self) -> int: ...
    @fit_to_height.setter
    def fit_to_height(self, value: int) -> None: ...
    @property
    def black_and_white(self) -> bool: ...
    @black_and_white.setter
    def black_and_white(self, value: bool) -> None: ...
