from typing import Any, Union
from ._openxlsx import XLDocument, XLProperty

class DocumentProperties:
    def __init__(self, doc: XLDocument) -> None: ...
    def __getitem__(self, key: Union[XLProperty, str]) -> Any: ...
    def __setitem__(self, key: Union[XLProperty, str], value: Any) -> None: ...
    def __delitem__(self, key: Union[XLProperty, str]) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def creator(self) -> str: ...
    @creator.setter
    def creator(self, value: str) -> None: ...
    @property
    def last_modified_by(self) -> str: ...
    @last_modified_by.setter
    def last_modified_by(self, value: str) -> None: ...
    @property
    def subject(self) -> str: ...
    @subject.setter
    def subject(self, value: str) -> None: ...
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str) -> None: ...
    @property
    def keywords(self) -> str: ...
    @keywords.setter
    def keywords(self, value: str) -> None: ...
    @property
    def category(self) -> str: ...
    @category.setter
    def category(self, value: str) -> None: ...
    @property
    def company(self) -> str: ...
    @company.setter
    def company(self, value: str) -> None: ...

class CustomProperties:
    def __init__(self, doc: XLDocument) -> None: ...
    def __getitem__(self, name: str) -> str: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __delitem__(self, name: str) -> None: ...
    def __contains__(self, name: str) -> bool: ...
