from typing import Any, Iterator, Optional
from ._openxlsx import XLCellRange
from .cell import Cell

class Range:
    __slots__ = ("_range", "_worksheet_ref")
    @property
    def _worksheet(self) -> Optional[Any]: ...
    def __init__(self, raw_range: XLCellRange, worksheet: Any = None) -> None: ...
    def __iter__(self) -> Iterator[Cell]: ...
    @property
    def address(self) -> str: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    def clear(self) -> None: ...
    async def clear_async(self) -> None: ...
