from typing import Any, Sequence

class StreamWriter:
    def __init__(self, native_writer: Any, workbook: Any = ...) -> None: ...
    def __enter__(self) -> StreamWriter: ...
    def __exit__(self, *args: Any) -> Any: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def last_row(self) -> int: ...
    @property
    def max_column(self) -> int: ...
    def close(self) -> None: ...
    def append_row(
        self, values: Sequence[Any], row_opts: Any = ...
    ) -> None: ...
    def set_row(
        self,
        row: int,
        start_col: int,
        values: Sequence[Any],
        row_opts: Any = ...,
    ) -> None: ...
    def set_row_ref(
        self, ref: str, values: Sequence[Any], row_opts: Any = ...
    ) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class StreamReader:
    def __init__(self, native_reader: Any) -> None: ...
    def __iter__(self) -> StreamReader: ...
    def __next__(self) -> Any: ...
    def __enter__(self) -> StreamReader: ...
    def __exit__(self, *args: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
