from typing import Any

class Table:
    def __init__(self, raw_table: Any, worksheet: Any = None) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def display_name(self) -> str: ...
    @display_name.setter
    def display_name(self, value: str) -> None: ...
    @property
    def range(self) -> str: ...
    @range.setter
    def range(self, value: str) -> None: ...
    @property
    def style(self) -> str: ...
    @style.setter
    def style(self, value: str) -> None: ...
    @property
    def show_row_stripes(self) -> bool: ...
    @show_row_stripes.setter
    def show_row_stripes(self, value: bool) -> None: ...
    @property
    def show_column_stripes(self) -> bool: ...
    @show_column_stripes.setter
    def show_column_stripes(self, value: bool) -> None: ...
    @property
    def show_first_column(self) -> bool: ...
    @show_first_column.setter
    def show_first_column(self, value: bool) -> None: ...
    @property
    def show_last_column(self) -> bool: ...
    @show_last_column.setter
    def show_last_column(self, value: bool) -> None: ...
    @property
    def show_totals_row(self) -> bool: ...
    @show_totals_row.setter
    def show_totals_row(self, value: bool) -> None: ...
    def append_column(self, name: str) -> None: ...
